// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UserInput struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
}
